### ISSUE TITLE
use sixel for video thumbnail

### ISSUE THREAD

**Issue by aicynide** [Aanok/jftui#38]
**jftui version**
Please include the output of `jftui --version`.

**Describe the bug**
Please include a clear and concise description of what the bug is.

**To Reproduce**
Please explain how you reached the point where the bug manifested.

**Expected behavior**
Please include a clear and concise description of what you expected to happen.

**SIGSEGV backtrace**
If you experienced a Segmentation Fault and a core dump was generated, please include a copy of the backtrace.
This [Arch Wiki article](https://wiki.archlinux.org/index.php/Core_dump#Examining_a_core_dump) applies to all systems using `coredumpctl`. Otherwise, you may refer to your distribution's documentation to locate the core dump or execute jftui directly through `gdb` and replicate the bug.

**Comment by Aanok** [comment]
Hi, I like the current interface because it's reasonably compact. I don't want a menu item to take multiple rows in the terminal unless it has to wrap around and building a sixel thumbnail that's only one character tall to preserve that would be fairly useless.

So I'll be rejecting this for the present time.
